### ISSUE TITLE
Local laplacian generator when using python JIT shows black image with target "host-cuda"

### ISSUE THREAD

**Issue by oliver-batchelor** [halide/Halide#7213]
**Describe the bug**

Local laplacian example when using JIT (`compile_to_callable`) shows black image when target is "host-cuda" (but works fine for "host"). Using prerelease pip wheel for Halide.

**To Reproduce**

Install Halide python from prerelease pip:

`pip install -i https://test.pypi.org/simple/ halide`

Put attached `local_laplacian_app.py `in `Halide/python_bindings/apps --target "host"`
[local_laplacian_app.py.txt](https://github.com/halide/Halide/files/10172535/local_laplacian_app.py.txt)

Run `python local_laplacian_app.py <some_image.jpg>  output.png` 
<output should show image after local laplacian filter>

Run ``python local_laplacian_app.py <some_image.jpg>  output.png --target "host-cuda" ` 
<output is a black image>

**Comment by steven-johnson** [comment]
Thanks for the report! 

I think that this issue is fixed in the most recent prerelease of Halide 15; unfortunately, our test script for building prerelease wheels is broken -- it needs to adapt to the fact that you can't replace an existing upload in test, and I haven't had the chance to fix it due to other work constraints (and the other maintainer of it is on a break from the project for another week or two). I'll bump this back up my list and try to get it fixed soon!

(Do you have the setup to build from source locally and test the result? If so, let me know.)

(BTW, how did you hear about Halide-via-pip? We haven't advertised it very widely yet, but we're keenly interested in feedback)

**Comment by oliver-batchelor** [comment]
So far extremely useful, and very easy to install and a few of us have tried it without issues.

Until I saw this, I did try to compile Halide a number of times for a conda python environment and each time had a couple of missing symbols from linking to LLVM (probably doing something wrong) - so this was just the ticket - especially for those of us just dipping toes in the water.

**Comment by oliver-batchelor** [comment]
As for how I heard about it - I spied it on the Gitter channel!

**Comment by oliver-batchelor** [comment]
@steven-johnson It's still the same with the latest version... 16.0 prerelease.

**Comment by steven-johnson** [comment]
OK, it looks like the fixes made in https://github.com/halide/Halide/pull/6869 should have been merged into the code path for Callable as well, but weren't; prepping a fix now

**Comment by steven-johnson** [comment]
See https://github.com/halide/Halide/pull/7472

**Comment by steven-johnson** [comment]
Also https://github.com/halide/Halide/pull/7473
