### ISSUE TITLE
Storage folding does not work when dimension is split

### ISSUE THREAD

**Issue by dvicini** [halide/Halide#738]
Hi,

It seems, that storage folding does not work when one of the dimensions is split. Code example:

```
int main(int argc, char **argv)
{
    Var u("u"), uo("uo"), ui("ui");

    Func f("f");
    f(u) = sqrt(u);

    Func g("g");
    g(u) = 1.5f * f(u);

    // Schedule 1: storage folding works without any problems and the buffer for f has size 1
    //g.compute_root();
    //f.compute_at(g, u).store_root();

    // Schedule 2: the buffer for f has size 512 instead of 32 (no storage folding)
    g.compute_root().split(u, uo, ui, 32);
    f.compute_at(g, uo).store_root();

    g.compile_to_simplified_lowered_stmt("storage_folding_bug.html", 512, HTML);

    Image<float> outputImg = g.realize(512);
    return 0;
}
```

In the first schedule, storage folding is applied successfully and the buffer allocated for f has size 1. In the other schedule it's not applied and the buffer allocated for f has the size 512 (according to to stmt output at least). Of course one could use f.compute_at(g, uo).store_at(g, uo) to get an allocation of the correct size, but this leads to a lot of overhead due to buffer allocation in every iteration of uo.

I think this is a bug in Halide, since the storage folding works if u is not split. Is there any workaround for this problem or is it easy to fix on the Halide side? 

Thanks for your help.

(My goal is to process tiles of the input separately because of memory restrictions, so I really need the storage folding here)

**Comment by dvicini** [comment]
I've managed to get correct storage folding by essentially doing all calculations for the split by hand:
	Var u("u"), uo("uo"), ui("ui");

	Func f("f");
	f(ui, uo) = sqrt(uo * 32 + ui);

	Func g("g");
	g(ui, uo) = 1.5f * f(ui, uo);

	Func h("h");
	h(u) = g(u % 32, u / 32);

	g.compute_root();
	f.compute_at(g, uo).store_root();

	h.compile_to_simplified_lowered_stmt("storage_folding_bug.html", 512, HTML);

	Image<float> outputImg = h.realize(512);

Halide manages to eliminate the divisions in the definition of h, since this is just a conversion from 1D to 2D coordinates. However, the solution is still far from optimal, since it really affects the code of the original algorithm and not only the scheduling....

**Comment by abadams** [comment]
Looking into it.

**Comment by abadams** [comment]
Some improvements can be made (and I'll push some), but perhaps what we
should really do here is hoist mallocs out of serial loops when the size
doesn't depend on the loop variable. It would be a pretty easy pass to
write. So far I've held off on this because it seems to contradict the
schedule's store_at directive.

On the other hand, malloc/free is very good at freeing and then
reallocating the same size buffer over and over. Putting the store_at
inside yo probably adds very little overhead. Have you profiled?

**Comment by dvicini** [comment]
Hi Andrew,

Thanks a lot for your quick help! I really appreciate it.

Yes, moving the malloc out of the loop in case the size is always the same seems to be a good idea. I mean that's exactly what I tried to achieve by using compute_at(..).store_root(). I think doing this automatically could cause confusion and maybe break very special schedules (?). What I currently miss a bit when it comes to storage folding, is manual control. As you may remember, I've run into storage folding issues before and had to ask for your help. It would be nice if there was some kind of manual fallback in case the automatic folding does not work. (even though the previous problem and also this problem could both be solved by doing manual index calculations, I don't think that they provide an actual alternative to the proper folding)

**Comment by dvicini** [comment]
I've now tried your changes and it seems to work (compiling Halide and llvm was less painful than I expected). I have yet to try them in my actual code.

Two questions though:
- Whats the best way to deal with arbitrary sized output buffers? I tried changing the bound to a multiple of the splitting factor which is larger than the output buffer size, but that gave me out of bounds access to the output buffer. Or should I just deal with this outside of the Halide code by realizing over a buffer which is large enough and crop later?

- I noticed that the following code works:

    g.bound(u, 0, (g.output_buffer().width() / 32) * 32).compute_root().split(u, uo, ui, 32);
    f.compute_at(g, uo).store_root();
but this one doesn't:
    g.bound(u, 0, (g.output_buffer().width() / 32) * 32).compute_root().split(u, uo, ui, 32);
    f.compute_at(g, uo).store_at(g, Var::outermost());

**Comment by abadams** [comment]
I've pushed a fix for the second thing.

The first thing is tricky. You can add an extra stage to the Halide
pipeline that does the crop, but it's probably better to find some other
schedule that has equivalent performance. Again, what is it actually
costing you in terms of performance to leave the malloc inside the loop? If
it's large we should more seriously look at allocation hoisting.

**Comment by zvookin** [comment]
@abadams Can this be closed?

**Comment by abadams** [comment]
Storage folding still isn't as aggressive as it could be when vars are split. Solving #1820 requires also solving this issue
