### ISSUE TITLE
Multiply-defined symbol errors when linking instances of the same Halide code with different schedules on Windows

### ISSUE THREAD

**Issue by jbosboom** [halide/Halide#740]
I'm compiling the Halide code below twice, once with the schedule included and once with it commented out, then running the resulting executables to produce .o files.  (My code decides at runtime which to call based on the actual input size.)  On the 2014/10/09 release, I can link these object files together without errors, but on the 2015/02/25 release, I get multiple definition errors.

I am using cl.exe 18.00.30501 for x86 (installed with Visual Studio 2013, though I am not using Visual Studio itself).  The compile-and-link command line is `cl.exe /O2 /Oy- /LD blurdll.dll halide_out_blur.o halide_out_blur_sched.o`.

If I link with `/force` to have the linker just take the first definition seen, the resulting code works (and is faster than the older release, yay!). However, the process that loads my DLL will not terminate unless manually forced using Task Manager, so this requires an actual fix somewhere.

````
#include <Halide.h>
#include <vector>
using namespace std;
using namespace Halide;

int main(){ 

Var x_0;
Var x_1;
ImageParam input_1(UInt(8),2);
Func output_2;
 output_2(x_0,x_1)  =  cast<uint8_t>(  ( (( 4  + ( 4  * cast<uint32_t>( input_1(x_0+1,x_1+1) )) + cast<uint32_t>( input_1(x_0+1,x_1) ) + cast<uint32_t>( input_1(x_0,x_1+1) ) + cast<uint32_t>( input_1(x_0+2,x_1+1) ) + cast<uint32_t>( input_1(x_0+1,x_1+2) )) >> cast<uint32_t>( 3 )) ) & 255 ) ;
    
Halide::Var _x_00, _x_11;
output_2
.split(x_0, x_0, _x_00, 32)
.split(x_1, x_1, _x_11, 8)
.reorder(_x_00, x_0, _x_11, x_1)
.reorder_storage(x_0, x_1)
.vectorize(_x_00, 8)
.parallel(x_1)
.compute_root()
;

 vector<Argument> args;
args.push_back(input_1);
output_2.compile_to_file("halide_out_blur_sched", args);
//output_2.compile_to_file("halide_out_blur", args);
return 0;
}
````

````
Microsoft (R) Incremental Linker Version 12.00.30501.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:blurdll.dll 
/dll 
/implib:blurdll.lib 
blurdll.obj 
halide_out_blur.o 
halide_out_blur_sched.o 
halide_out_blur_sched.o : error LNK2005: _halide_start_clock already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_reference_clock_inited already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_reference_clock already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_clock_frequency already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_current_time_ns already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal17halide_print_implEPvPKc already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal10init_mutexEPyPvPS3_@12 already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal16InitOnceCallbackEPyPvPS3_@12 already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal17halide_work_queueE already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal15default_do_taskEPvPFiS2_iPhEiS3_ already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal20halide_worker_threadEPv already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_do_task already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal21halide_custom_do_taskE already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal18default_do_par_forEPvPFiS2_iPhEiiS3_ already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal30halide_thread_pool_initializedE already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal18halide_num_threadsE already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_mutex_cleanup already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_mutex_lock already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_mutex_unlock already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_shutdown_thread_pool already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_posix_thread_pool_cleanup already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_set_num_threads already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_set_custom_do_task already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_set_custom_do_par_for already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal24halide_custom_do_par_forE already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_do_par_for already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_set_gpu_device already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal17halide_gpu_deviceE already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal29halide_gpu_device_initializedE already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_get_gpu_device already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal22halide_gpu_device_lockE already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal13default_traceEPvPK18halide_trace_event already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_get_trace_file already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_error already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_print already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal22halide_trace_file_lockE already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal29halide_trace_file_initializedE already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_set_trace_file already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal35halide_trace_file_internally_openedE already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal17halide_trace_fileE already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_set_custom_trace already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal19halide_custom_traceE already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_trace already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_shutdown_trace already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_trace_cleanup already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_string_to_string already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_int64_to_string already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_uint64_to_string already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_double_to_string already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_pointer_to_string already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal18has_tiff_extensionEPKc already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_debug_to_file already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal30pixel_type_to_tiff_sample_typeE already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal14default_mallocEPvj already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal12default_freeEPvS2_ already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_set_custom_malloc already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal13custom_mallocE already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_set_custom_free already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal11custom_freeE already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_malloc already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_free already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal21default_error_handlerEPvPKc already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal20halide_error_handlerE already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_set_error_handler already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal19halide_custom_printE already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_set_custom_print already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal11full_extentERK8buffer_t already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal12copy_from_toEPvRK8buffer_tRS3_ already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal14copy_of_bufferEPvRK8buffer_t already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal10keys_equalEPKhS3_j already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal12bounds_equalERK8buffer_tS4_ already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal10CacheEntry4initEPKhjjRK8buffer_tiPPS5_ already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal10CacheEntry6bufferEi already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal10CacheEntry7destroyEv already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_device_free already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal8djb_hashEPKhj already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal11prune_cacheEv already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal18current_cache_sizeE already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal19least_recently_usedE already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal14max_cache_sizeE already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal13cache_entriesE already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal18most_recently_usedE already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_memoization_cache_set_size already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal16memoization_lockE already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_memoization_cache_lookup already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_memoization_cache_store already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_memoization_cache_cleanup already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_cache_cleanup already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal27copy_to_host_already_lockedEPvP8buffer_t already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_get_device_interface already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_new_device_wrapper already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_delete_device_wrapper already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_get_device_handle already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_device_release already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_copy_to_host already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: __ZN6Halide7Runtime8Internal17device_copy_mutexE already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_copy_to_device already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_device_malloc already defined in halide_out_blur.o
halide_out_blur_sched.o : error LNK2005: _halide_device_sync already defined in halide_out_blur.o
blurdll.dll : fatal error LNK1169: one or more multiply defined symbols found
````

**Comment by abadams** [comment]
The multiply-defined symbols thing is expected. On linux and os x this gets
resolved silently using weak symbols, but that doesn't work on windows. We
typically just use /force. But you say the process won't terminate? What is
it doing if you break into it in the debugger?

Perhaps the change is the static destructors we added to the runtime.

btw, you can also compile multiple schedules and switch between them using
Func::specialize on a Param.

**Comment by jbosboom** [comment]
There's just one thread left in the process, stuck with the following stack trace:
````
0:000> kb
ChildEBP RetAddr  Args to Child              
02fff590 77283255 00000000 280bfe70 00000000 ntdll!NtReleaseKeyedEvent+0x15
*** WARNING: Unable to verify checksum for C:\Users\kevin\Downloads\blurdll.dll
02fff5b0 6bab175d 6bad9298 00000000 6bad11a0 ntdll!RtlWakeAllConditionVariable+0x66
02fff5cc 6bab7c78 030ba054 77239dd5 030ba058 blurdll!halide_shutdown_thread_pool+0x4d
02fff5e0 6bab7da5 6bad119c 6bad11b8 92f91f6d blurdll!_initterm+0x29 [f:\dd\vctools\crt\crtw32\startup\crt0dat.c @ 954]
02fff62c 6bab7b0f 00000000 00000000 00000001 blurdll!doexit+0xec [f:\dd\vctools\crt\crtw32\startup\crt0dat.c @ 651]
02fff63c 6babb64e 92f91f2d 00000001 00000000 blurdll!_cexit+0xb [f:\dd\vctools\crt\crtw32\startup\crt0dat.c @ 448]
02fff66c 6babb7e7 6bab0000 00000000 00000001 blurdll!_CRT_INIT+0xb3 [f:\dd\vctools\crt\crtw32\startup\dllcrt0.c @ 169]
02fff6ac 6babb729 6bab0000 00000000 00000001 blurdll!__DllMainCRTStartup+0xb7 [f:\dd\vctools\crt\crtw32\startup\dllcrt0.c @ 399]
02fff6c0 772399a0 6bab0000 00000000 00000001 blurdll!_DllMainCRTStartup+0x1c [f:\dd\vctools\crt\crtw32\startup\dllcrt0.c @ 340]
02fff6e0 7724d702 6babb70d 6bab0000 00000000 ntdll!LdrpCallInitRoutine+0x14
02fff784 7724d5a4 04a0ae5c 77239dd5 04a0ae60 ntdll!LdrShutdownProcess+0x1aa
02fff798 76bc79ec 00000000 77e8f3b0 ffffffff ntdll!RtlExitUserProcess+0x74
02fff7ac 6f2a7997 00000000 02fff7fc 6f2a7ab0 kernel32!ExitProcessStub+0x12
02fff7b8 6f2a7aaf 00000000 7095873f 0264cff8 MSVCR100!__crtExitProcess+0x17
02fff7fc 6f2a7b1d 00000000 00000000 00000000 MSVCR100!_cinit+0x145
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for C:\Program Files (x86)\Adobe\Adobe Photoshop CS6\Photoshop.exe - 
02fff810 0123c04b 00000000 70944a4f 00000000 MSVCR100!exit+0x11
WARNING: Stack unwind information not available. Following frames may be wrong.
02fff898 76bc338a fffde000 02fff8e4 77239f72 Photoshop!std::_Mutex::_Mutex+0xa2d
02fff8a4 77239f72 fffde000 5c11ee65 00000000 kernel32!BaseThreadInitThunk+0xe
02fff8e4 77239f45 0123c17a fffde000 00000000 ntdll!__RtlUserThreadStart+0x70
02fff8fc 00000000 0123c17a fffde000 00000000 ntdll!_RtlUserThreadStart+0x1b
````
I don't know what to type to get more information on the conditional variable object and "windbg condition variable" is not helpful, sorry.

**Comment by aam** [comment]
Jeffrey,

  just curious, have you tried building/running your app using latest
Halide with just one instance of your Halide filter linked in?
  Confirming that it works(or doesn't) might help narrow down potential
cause for hanging.

Alex.

**Comment by abadams** [comment]
That looks like we're hanging inside cleaning up the thread pool - we can't
trigger the condition variable that wakes up all the threads and tells them
the game is over because the condition variable itself is already kaput. If
you compile Halide yourself you can just comment out the function marked
with attribute destructor in windows_thread_pool.cpp

**Comment by jbosboom** [comment]
I've switched to using Func::specialize to avoid the duplicate symbol errors.  I still have the hang-on-exit problem with my injected DLLs, but standalone executables exit correctly, so I think the hangs are due to some interaction between my DLLs and the host program (which is not expecting to host them).

Thanks for your help and sorry for the noise.
